export const TOGGLE_LOCATION = 'TOGGLE_LOCATION';
export const TOGGLE_CATEGORIES = 'TOGGLE_CATEGORIES';
export const TOGGLE_START_DATE = 'TOGGLE_START_DATE';
export const TOGGLE_END_DATE = 'TOGGLE_END_DATE';
