export const START_LOADING_DATA = 'START_LOADING_DATA';
export const DONE_LOADING_DATA = 'DONE_LOADING_DATA';
export const START_LOADING_MAP = 'START_LOADING_MAP';
export const DONE_LOADING_MAP = 'DONE_LOADING_MAP';
