/**
 * @fileoverview This file lets the Search Component keep track of whats
 * being filtered. The source of this data is from the Filters Component,
 * where it will then be sent to the SearchBarContainer for 
 * query building and the SearchResultsContainer to show what 
 * is being filtered.
 */

import React from 'react';
import moment from 'moment';
import { debounce } from 'throttle-debounce';

import fetchRetry from '../../../../utils/fetchRetry';
import { CATEGORIES } from '../../constants/categories';

import Search from '../../components/Search/index';

export default class SearchContainer extends React.Component {
  state = {
    filters: {
      // Filter for events within the circle specified
      // by these values
      locationFilter: {
        latitude: '',
        longitude: '',
        radius: 1000000,
      },
      // Filter for events of the following categories
      categoriesFilter: Object.keys(CATEGORIES),
      // Filter for events after this date
      startDateFilter: 1325463472000,
      // Filter for events before this date
      endDateFilter: moment().valueOf(),
    },
    isLoading: false,
    error: false,
  }

  // SETTERS FOR STATE FIELDS

  setLatitude = (latitude) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        locationFilter: {
          ...prevState.locationFilter,
          latitude,
        },
      },
    }));
  }

  setLongitude = (longitude) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        locationFilter: {
          ...prevState.locationFilter,
          longitude,
        },
      },
    }));
  }

  setRadius = (radius) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        locationFilter: {
          ...prevState.locationFilter,
          radius,
        },
      },
    }));
  }

  setCategories = (categories) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        categoriesFilter: categories,
      },
    }));
  }

  setStartDate = (startDate) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        startDateFilter: moment(startDate).valueOf(),
      },
    }));
  }

  setEndDate = (endDate) => {
    this.setState(prevState => ({
      filters: {
        ...prevState.filters,
        endDateFilter: moment(endDate).valueOf(),
      },
    }));
  }

  startLoading = () => {
    this.setState(({
      isLoading: true,
    }));
  }

  doneLoading = () => {
    this.setState(({
      isLoading: false,
    }));
  }

  setError = () => {
    this.setState(({
      error: true,
    }));
  }

  removeError = () => {
    this.setState(({
      error: false,
    }));
  }

  /**
   * Sends a search query generated by the value inside the
   * searchbar and the filters being used. The results are
   * then used to update the application's events.
   */
  sendQuery = (title) => {
    // Remove any lingering error tags
    this.removeError();
    // Set the loading tag to true
    this.startLoading();
    // Fetch events from the API
    fetchRetry(`http://localhost:3000/api/events?title=${title}&${this.addFilterQuery()}`)
      .then(events => this.props.setEvents(events))
      // Catch in fetch only handles 'network errors'. Handling of errors
      // will be done in the above codeblock
      .catch(() => this.setError())
      .finally(this.doneLoading());
  };

  debouncedSendQuery = debounce(500, this.sendQuery);

  /**
   * @returns 
   *  A query string built from the filter parameters.
   */
  addFilterQuery = () => {
    const queryArray = [];
    const {
      locationFilter,
      categoriesFilter,
      startDateFilter,
      endDateFilter,
    } = this.state.filters;
    // We want all three to be defined to filter by location
    if (locationFilter.latitude && locationFilter.longitude && locationFilter.radius) {
      queryArray.push(`lat=${locationFilter.latitude}`);
      queryArray.push(`long=${locationFilter.longitude}`);
      queryArray.push(`radius=${locationFilter.radius}`);
    }
    if (categoriesFilter) {
      queryArray.push(`categories=${categoriesFilter.join(',')}`);
    }
    if (startDateFilter) {
      queryArray.push(`startDate=${startDateFilter}`);
    }
    if (endDateFilter) {
      queryArray.push(`endDate=${endDateFilter}`);
    }
    return queryArray.join('&');
  }

  render() {
    const { filters, isLoading, error } = this.state;
    return (
      <Search
        events={this.props.events}
        setFilters={{
          latitude: this.setLatitude,
          longitude: this.setLongitude,
          radius: this.setRadius,
          categories: this.setCategories,
          startDate: this.setStartDate,
          endDate: this.setEndDate,
        }}
        filters={filters}
        addFilterQuery={this.addFilterQuery}
        isLoading={isLoading}
        error={error}
        debouncedSendQuery={this.debouncedSendQuery}
      />
    );
  }
}
