const SOURCES = {
  AVO: 'Alaska Volcano Observatory',
  ABFIRE: 'Alberta Wildfire',
  AU_BOM: 'Australia Meteorology',
  BYU_ICE: 'Brigham Iceberg Tracker',
  BCWILDFIRE: 'British Columbia Wildfire Service',
  CALFIRE: 'California Fire Department',
  CEMS: 'Copernicus Emergency Service',
  EO: 'Earth Observatory',
  FEMA: 'Federal Emergency Management',
  FloodList: 'FloodList',
  GDACS: 'Global Disaster Alert System',
  GLIDE: 'Global Identifier Number',
  InciWeb: 'InciWeb',
  IDC: 'International Charter on Major Disasters',
  JTWC: 'Joint Typhoon Warning Center',
  MRR: 'LANCE Rapid Response',
  MBFIRE: 'Manitoba Fire Program',
  NASA_ESRS: 'NASA Remote Sensing Unit',
  NASA_DISP: 'NASA Disasters Program',
  NOAA_NHC: 'National Hurricane Center',
  NOAA_CPC: 'Center for Weather Prediction',
  PDC: 'Pacific Disaster Center',
  ReliefWeb: 'ReliefWeb',
  SIVolcano: 'Global Volcanism Program',
  NATICE: 'US National Ice Center',
  UNISYS: 'Unisys Weather',
  USGS_EHP: 'USGS Earthquake Hazards Program',
  USGS_CMT: 'USGS Emergency Operations Management',
  HDDS: 'USGS Hazards Data System',
  DFES_WA: 'Western Australia Fire and Emergency Services',
};

export default SOURCES;
